# Main settings
baseurl: ''
url: https://womanonrails.com


# Jekyll settings
exclude: ['.keep', '.ruby-gemset', '.ruby-version', '.sass-cache', '_drafts', '_templates', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
locale: en
include: ['_pages']
markdown: kramdown
permalink: /:title


# Plugins settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-multiple-languages-plugin
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Author settings
author: &author womanonrails
logo: womanonrails-square.svg
title: Woman on Rails


owner:
  name: Agnieszka Matysek
  avatar: womanonrails-square.svg
  email: please-do-not-spam-me@womanonrails.com
  description: 'Woman, programmer, mentor, speaker, photographer and dancer with passion.'
  twitter: *author
  facebook: *author
  github: *author
  linkedin: *author
  instagram: *author
  stackoverflow: https://stackoverflow.com/users/2885676/womanonrails


disqus_shortname: womanonrails
# Assign a default image for your site's header and footer
default_bg:
search:           true
share:            true
# Turn on or off the fin animations in the header and footer
triangleheader:   true
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"

meta:
  image: womanonrails-1000x1000.jpg

# Analytics and webmaster tools stuff goes here
google_analytics: UA-127731573-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Programming courses
    url: /workshops
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About
    url: /about

links_pl:
  - title: Strona główna
    url: /pl
    external: false
    icon: home
  - title: Kursy programowania
    url: /workshops
  - title: Kategorie
    url: /pl/categories
  - title: Tagi
    url: /pl/tags
  - title: O mnie
    url: /pl/about


# Layout settings
readtime: true
wpm: 200


defaults:
  # _pages
  - scope:
      path: ''
      type: pages
    values:
      comments: true
      read_time: false
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      comments: true
      read_time: true
      related: true
      share: true


sass:
  style: :compressed


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
paginate:    6
paginate_path: "page:num"


# Polyglot settings
default_lang: en
exclude_from_localizations: ['css', 'images', 'javascript']
languages: ['en', 'pl']
parallel_localization: true

feed:
  excerpt_only: true
